In [3]:
from base import np, plt

R_dtm = 1
R_inf = 1_000
L     = 10
Tc    = 1e-2
nr    = 100_000
n_r0  = n_l = 250

In [ ]:
(R_inf - R_dtm)/(nr - 1)

0.00999009990099901

In [4]:
R_inf/nr

0.01

In [13]:
np.logspace(1, 3, 10), np.linspace(1, 3, 10)

(array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
          77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
         599.48425032, 1000.        ]),
 array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
        2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ]))

In [14]:
np.logspace(np.log10(1), np.log10(3), 10)

array([1.        , 1.12983096, 1.27651801, 1.44224957, 1.62949822,
       1.84105755, 2.08008382, 2.35014311, 2.65526446, 3.        ])